# Generated by Django 2.2.3 on 2020-04-10 02:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer_model', '0004_auto_20200407_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer_C2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15)),
                ('subtypecod', models.BigIntegerField(blank=True, null=True)),
                ('op_volt', models.CharField(max_length=2)),
                ('facilityid', models.CharField(max_length=13)),
                ('phasedesig', models.BigIntegerField(blank=True, null=True)),
                ('ratekva', models.FloatField(blank=True, null=True)),
                ('owner', models.CharField(max_length=1)),
                ('presenttap', models.CharField(max_length=1)),
                ('customerty', models.CharField(max_length=1)),
                ('loadstatus', models.IntegerField(blank=True, null=True)),
                ('phasea_kva', models.FloatField(blank=True, null=True)),
                ('phaseb_kva', models.FloatField(blank=True, null=True)),
                ('phasec_kva', models.FloatField(blank=True, null=True)),
                ('capnum', models.IntegerField(blank=True, null=True)),
                ('totalkvar', models.IntegerField(blank=True, null=True)),
                ('lanum', models.IntegerField(blank=True, null=True)),
                ('constructi', models.CharField(max_length=1)),
                ('location', models.CharField(max_length=50)),
                ('angle', models.FloatField(blank=True, null=True)),
                ('transforme', models.IntegerField(blank=True, null=True)),
                ('installati', models.IntegerField(blank=True, null=True)),
                ('feederid', models.CharField(max_length=7)),
                ('feederid2', models.CharField(max_length=7)),
                ('feederinfo', models.BigIntegerField(blank=True, null=True)),
                ('enabled', models.IntegerField(blank=True, null=True)),
                ('wbs', models.CharField(max_length=55)),
                ('existingkw', models.FloatField(blank=True, null=True)),
                ('existingkv', models.FloatField(blank=True, null=True)),
                ('existing_1', models.FloatField(blank=True, null=True)),
                ('numberofus', models.BigIntegerField(blank=True, null=True)),
                ('attachment', models.CharField(max_length=254)),
                ('matrefno', models.CharField(max_length=30)),
                ('impact', models.CharField(blank=True, max_length=500, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
