# Generated by Django 2.2.3 on 2020-04-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformer_model', '0005_transformer_c2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transformer_PBA_Views',
        ),
    ]
