# Generated by Django 2.2.3 on 2020-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer_model', '0006_delete_transformer_pba_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformer_c2',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='transformer_c2',
            name='impact',
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='area_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='circuitcou',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='code',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='configurat',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='creation_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='creationus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='datecrea_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='datecreate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='datemodi_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='datemodifi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='designid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='designid_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='designtext',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='electrictr',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='fid_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='globalid',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='graphicdes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='labeltext',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='lastuser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='lastuser_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='objectid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='objectid_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='opvoltint',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='shape_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='shape_leng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='workflow_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='workflowst',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='workfunc_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='workfuncti',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='workloca_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='worklocati',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='workrequ_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transformer_c2',
            name='workreques',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='attachment',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='constructi',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='customerty',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='facilityid',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='feederid',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='feederid2',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='matrefno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='op_volt',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='owner',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='presenttap',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='tag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_c2',
            name='wbs',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='attachment',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='configurat',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='constructi',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='creationus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='customerty',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='designid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='designtext',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='facilityid',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='feederid',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='feederid2',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='graphicdes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='labeltext',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='lastuser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='matrefno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='op_volt',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='owner',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='presenttap',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='tag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='wbs',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='worklocati',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transformer_pba',
            name='workreques',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
