# Generated by Django 2.2.3 on 2020-04-11 15:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aoj_C2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=14)),
                ('workreques', models.CharField(max_length=20)),
                ('designid', models.CharField(max_length=20)),
                ('worklocati', models.CharField(max_length=20)),
                ('area_code', models.CharField(max_length=2)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
